# Generated by Django 5.1 on 2024-08-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_title_blog_titl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='titl',
            new_name='title',
        ),
    ]
