# Generated by Django 5.1.2 on 2024-10-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='catigory',
            new_name='category',
        ),
    ]
